language: java
os:
  - linux
 # openjdk cant build Java FX currently alone
jdk:
  - oraclejdk8
#  - openjdk8
  - oraclejdk9
#  - openjdk9
  - oraclejdk10
#  - openjdk10
#  - openjdk11
addons:
  apt:
    packages:
      - tree
#      - openjf
before_script:
  cd java
script:
  mvn install -Dmaven.javadoc.skip=true -B -V
after_script:
  cd .. && tree && cat java/target/dependency-check-report.html
